### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by JFGHT** [lupas/nuxt-fire-vuexfire-example#4]
Hi there @lupas.

Internally, [this](https://github.com/lupas/nuxt-fire-vuexfire-example/blob/d3139eb80f57be198c26a803c3af3199f289c62e/pages/index.vue#L30) line is using the snapshot API, which I guess, leaves the connection open for a later on update if any change is there.

Could not that possible cause a memory leak in the server?

Wouldn't it be better not to use any bindings for the `fetch` (SSR) step and just use a normal `get()` (with of course some custom actions/mutations)?

Thanks.

**Comment by lupas** [comment]
Hey there @JFGHT

Good catch, you might actually be right!
Just using regular get() will just make it less elegant... I came up with this new solution by directly unbinding the listener on the server, what do you think about that?

https://github.com/lupas/nuxt-fire-vuexfire-example/blob/master/pages/index.vue#L33

**Comment by JFGHT** [comment]
Theoretically, this should work but when it comes to elegancy... I disagree.

I'm still unfamiliar with Nuxt api, so take this suggestion with a grain of salt.

In my opinion, we should just probably do a direct commit to the store with the result of the `get()` since action -> mutation flow is unnecessary here because we cannot track it - it happens in the backend -, so all features (like timetravel) are gone. And, because we are going to have to repeat this two "queries" allover again in the two life cycles (fetch and created/mounted), it's kind of verbose. Is there any way in Nuxt (like a middleware or something) that would do this for selected components?

**Comment by lupas** [comment]
@JFGHT 
You're right, it is for sure more performant that way. With elegant here I meant less code, but for sure not the "smarter" way ;-)

I added both examples to the repo, have a look:

**SSR Direct Mutation**
https://github.com/lupas/nuxt-fire-vuexfire-example/blob/master/pages/ssr-direct/index.vue

Directly mutating state is imho a personal decision and has not anything to do with Firebase. Even though it's on the server I still prefer using a mutation instead of directly mutating. But yes, an action is imho not needed.

**SSR through vuexfire**
https://github.com/lupas/nuxt-fire-vuexfire-example/blob/master/pages/ssr-direct/index.vue

Less performant, but simple to implement. For prototyping and smaller projects imho totally okay.

**Comment by JFGHT** [comment]
I think you pasted same link twice, if I'm not mistaken. But yeah, that should be the short-term solution!

I didn't mean directly mutating the state, I think I made a explaining mistake there, I meant exactly what you did; commiting directly without an action.

Still, there is one huge drawback here: references. If some of your logic depends on the "expanded" references automatically made by `vuexfire`, this is clearly not the solution you need. You would still have to go back and do your first approach: bind and unbind.

Maybe a generic solution here would need a bit more code that expected. Maybe kind of a configurable thing in your `firebase-module`?

**Comment by lupas** [comment]
@JFGHT 
Just fixed the link, thanks. 😺 

What do you mean by `automatically made by vuexfire`? We define the reference in the vuexfire store action the same way as in the fetch() method.

If you want you can always declare the reference in a separate module and then just import it wherever needed, so you won't have to declare it twice.

I don't see a big drawback in that?

I'm happy to  improve the firebase module in any  way that helps, regarding this topic I don't really see how the module could make life easier though... Glad for any suggestions :)

**Comment by JFGHT** [comment]
I meant deeper references. For example, you bind a doc that has a reference to another doc. If I'm not mistaken, `vuexfire `automatically "expands" the second reference (probably binding recursively) and you have it there to use it in the store accessing via the very first doc (the one you binded).

Thanks for your efforts, specially the module is such a pain reliever :D.

**Comment by lupas** [comment]
@JFGHT 
Aaahh I see! Ouch, I wasn't even aware of that functionality in vuexfire. 😆 

Yes, in that case it will be much simpler to use the **SSR through vuexfire** method. If one is going that way it would for sure make sense to do some tests on how bad it is performance wise. Maybe it's not that bad?

**@nuxt/firebase** is meant to easily implement Firebase into Nuxt, I don't see adding  not nuxt-specific features to it. And what we need here would be a simple function that automatically fetches all the linked documents, linke vuexfire does.

I have a very fameless helper module [firewings](https://firewings.netlify.app/) where I think this would actually be a great addition.

I could add an option to the **[queryFirestore()](https://firewings.netlify.app/functions/firestore/#queryfirestore)** function that would automatically get() attached references down to a certain depth, that would be a great addition.

Not a bad idea... :)

Thanks for your input btw!

**Comment by JFGHT** [comment]
Paid you a coffee ;). By the way, I saw your profile and read you're a world-traveler, which is something I'm considering. Would you like to have a conversation via Telegram or something?

PS: I'll remove this comment later.

**Comment by lupas** [comment]
@JFGHT 
I appreciate that a lot, thank you so much! :)
Sure, I'm happy to. Not really using Telegram, you can find me there via [https://t.me/pascalluther](https://t.me/pascalluther).

I travelled for the past year continuously but stopped for now, working in Switzerland for 1-2 years since I got good job offer (and the COVID situation), but thinking of moving again after that. It's the best thing you can do, living out in the world and just moving around... can't wait to leave again :P

Thanks again for the coffee! :D Talk later!

PS: Also gonna delete that comment after it is sent.

**Comment by lupas** [comment]
@JFGHT 
Not sure if you got my message yesterday, I deleted it after a while, too.

Thanks a lot for the GitHub sponsor contribution, I really appreciate it! :-)

I just finished about a year of travelling and am now back home for a year or two, but for sure will go out explore the world again after that. Happy to talk more, just hit me a message on Telegram "pascalluther".

Talk soon.

PS:  Will leave it until you see it this time, let me know when you got it :)
