### ISSUE TITLE
[Question] Selecting implementation type

### ISSUE THREAD

**Issue by RobSteward** [lupas/nuxt-fire-vuexfire-example#5]
Hi lupas,

thanks for adding those three implementation examples. Would it be possible to add a quick explanation as to when to choose which type of implementation and things to consider/risk vs benefits?

My specific question: It looks like the SPA version is the most reduced (in terms of lines), logical and "sound" (aka the store being the single source of thruth and handling all database updates which the client does not really talk to). Can I and should I go for the SPA implementation while using a nuxt in universal mode?

**Comment by sambessey** [comment]
Sorry I can't help answer this, but just want to say I had exactly the same question - so any help would be great!

**Comment by rajesh-h** [comment]
@RobSteward did you get any ideas on this?

I have planned for application where I develop it as universal mode but production version will have completely offline generated mode with only admin routes will be excluded from generation routes.

I have login to be implemented but confused on which Version or mode I should be going with

**Comment by RobSteward** [comment]
@rajesh-h Sorry mate - non further information on this. I went with universal.

**Comment by sambessey** [comment]
I did the same @rajesh-h . All working well for me. Hopefully you'll have a similar experience.

**Comment by rajesh-h** [comment]
Thank you very much @sambessey . I do have some teething problems. Hopefully I will be able to resolve them.

**Comment by SKFrozenCloud** [comment]
**spa-mode** - SPA/Universal mode. Use this if you are not using SSR.

**ssr-direct** - SSR capabilities by using the native API (https://firebase.nuxtjs.org/service-options/firestore)

**ssr-vuexfire** - SSR capabilities with vuexfire.

Use **spa-mode** if you don't use ssr.
Use **ssr-vuexfire** if you do use ssr since it's more direct and simpler.

**Comment by lupas** [comment]
Hey Guys

Sorry for the late response - for some reason I did not get any notifications for new issues on this repository.

Which mode to choose is nothing related to Vuex or Firebase or Auth. This has to do with what kind of application you want to build and how you want to deploy it.

So this is basically a Nuxt related question - please refer to the Nuxt Documentation to read about the [SSR mode](https://nuxtjs.org/docs/2.x/concepts/server-side-rendering) and the [Static mode](https://nuxtjs.org/docs/2.x/concepts/static-site-generation) - this should make it pretty clear what that is all about.

We here simply show examples on how to implement this in these various modes - some are more verbose and some not, because there are various things (like having a backend server or not) have to be considered.

If you have further questions regarding the Nuxt modes I would suggest you to ask them in the Nuxt Community Discord channel.
